# Generated by Django 4.1.6 on 2023-02-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleet',
            name='driver',
        ),
        migrations.AddField(
            model_name='driver',
            name='cars',
            field=models.ManyToManyField(related_name='drivers', to='fleet.fleet'),
        ),
    ]
